services:
    stev.lista_firme:
        class: Stev\ListaFirmeBundle\Lib\ListaFirme
        arguments: [%stev_lista_firme.username%, %stev_lista_firme.password%]

    stev.lista_firme.validator.is_valid_company:
        class: Stev\ListaFirmeBundle\Validator\Constraints\IsValidCompanyValidator
        tags:
            - { name: validator.constraint_validator, alias: is_valid_company }