services:
    Stev\ListaFirmeBundle\Lib\CIFChecker:
        class: Stev\ListaFirmeBundle\Lib\CIFChecker
        arguments:
            - '%stev_lista_firme.cifChecker%'
            - '%stev_lista_firme.username%'
            - '%stev_lista_firme.password%'
            - '@logger'
            - '%stev_lista_firme.offline%'
            - '%stev_lista_firme.enabled%'
            - '%stev_lista_firme.apiKey%'

    Stev\ListaFirmeBundle\Validator\Constraints\IsValidCompanyValidator:
        class: Stev\ListaFirmeBundle\Validator\Constraints\IsValidCompanyValidator
        arguments: ['@Stev\ListaFirmeBundle\Lib\CIFChecker','@logger']
        tags:
            - { name: validator.constraint_validator, alias: is_valid_company }
