services:
    stev.lista_firme:
        class: Stev\ListaFirmeBundle\Lib\CIFChecker
        arguments:
            - %stev_lista_firme.cifChecker%
            - %stev_lista_firme.username%
            - %stev_lista_firme.password%
            - %stev_lista_firme.offline%
            - %stev_lista_firme.enabled%
            - %stev_lista_firme.pathToPhantom%
            - '@logger'
            - %stev_lista_firme.apiKey%

    stev.lista_firme.validator.is_valid_company:
        class: Stev\ListaFirmeBundle\Validator\Constraints\IsValidCompanyValidator
        arguments: ['@stev.lista_firme']
        tags:
            - { name: validator.constraint_validator, alias: is_valid_company }